/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as StudioRouteImport } from './routes/studio'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiChatRouteImport } from './routes/api/chat'
import { Route as ApiPikaStatusRouteImport } from './routes/api/pika/status'
import { Route as ApiPikaDisconnectRouteImport } from './routes/api/pika/disconnect'
import { Route as ApiPikaConnectRouteImport } from './routes/api/pika/connect'
import { Route as ApiAssetIdRouteImport } from './routes/api/asset.$id'
import { Route as ApiPikaOauthCallbackRouteImport } from './routes/api/pika/oauth.callback'

const StudioRoute = StudioRouteImport.update({
  id: '/studio',
  path: '/studio',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiChatRoute = ApiChatRouteImport.update({
  id: '/api/chat',
  path: '/api/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPikaStatusRoute = ApiPikaStatusRouteImport.update({
  id: '/api/pika/status',
  path: '/api/pika/status',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPikaDisconnectRoute = ApiPikaDisconnectRouteImport.update({
  id: '/api/pika/disconnect',
  path: '/api/pika/disconnect',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPikaConnectRoute = ApiPikaConnectRouteImport.update({
  id: '/api/pika/connect',
  path: '/api/pika/connect',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAssetIdRoute = ApiAssetIdRouteImport.update({
  id: '/api/asset/$id',
  path: '/api/asset/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPikaOauthCallbackRoute = ApiPikaOauthCallbackRouteImport.update({
  id: '/api/pika/oauth/callback',
  path: '/api/pika/oauth/callback',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/studio': typeof StudioRoute
  '/api/chat': typeof ApiChatRoute
  '/api/asset/$id': typeof ApiAssetIdRoute
  '/api/pika/connect': typeof ApiPikaConnectRoute
  '/api/pika/disconnect': typeof ApiPikaDisconnectRoute
  '/api/pika/status': typeof ApiPikaStatusRoute
  '/api/pika/oauth/callback': typeof ApiPikaOauthCallbackRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/studio': typeof StudioRoute
  '/api/chat': typeof ApiChatRoute
  '/api/asset/$id': typeof ApiAssetIdRoute
  '/api/pika/connect': typeof ApiPikaConnectRoute
  '/api/pika/disconnect': typeof ApiPikaDisconnectRoute
  '/api/pika/status': typeof ApiPikaStatusRoute
  '/api/pika/oauth/callback': typeof ApiPikaOauthCallbackRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/studio': typeof StudioRoute
  '/api/chat': typeof ApiChatRoute
  '/api/asset/$id': typeof ApiAssetIdRoute
  '/api/pika/connect': typeof ApiPikaConnectRoute
  '/api/pika/disconnect': typeof ApiPikaDisconnectRoute
  '/api/pika/status': typeof ApiPikaStatusRoute
  '/api/pika/oauth/callback': typeof ApiPikaOauthCallbackRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/studio'
    | '/api/chat'
    | '/api/asset/$id'
    | '/api/pika/connect'
    | '/api/pika/disconnect'
    | '/api/pika/status'
    | '/api/pika/oauth/callback'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/studio'
    | '/api/chat'
    | '/api/asset/$id'
    | '/api/pika/connect'
    | '/api/pika/disconnect'
    | '/api/pika/status'
    | '/api/pika/oauth/callback'
  id:
    | '__root__'
    | '/'
    | '/studio'
    | '/api/chat'
    | '/api/asset/$id'
    | '/api/pika/connect'
    | '/api/pika/disconnect'
    | '/api/pika/status'
    | '/api/pika/oauth/callback'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  StudioRoute: typeof StudioRoute
  ApiChatRoute: typeof ApiChatRoute
  ApiAssetIdRoute: typeof ApiAssetIdRoute
  ApiPikaConnectRoute: typeof ApiPikaConnectRoute
  ApiPikaDisconnectRoute: typeof ApiPikaDisconnectRoute
  ApiPikaStatusRoute: typeof ApiPikaStatusRoute
  ApiPikaOauthCallbackRoute: typeof ApiPikaOauthCallbackRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/studio': {
      id: '/studio'
      path: '/studio'
      fullPath: '/studio'
      preLoaderRoute: typeof StudioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/chat': {
      id: '/api/chat'
      path: '/api/chat'
      fullPath: '/api/chat'
      preLoaderRoute: typeof ApiChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/pika/status': {
      id: '/api/pika/status'
      path: '/api/pika/status'
      fullPath: '/api/pika/status'
      preLoaderRoute: typeof ApiPikaStatusRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/pika/disconnect': {
      id: '/api/pika/disconnect'
      path: '/api/pika/disconnect'
      fullPath: '/api/pika/disconnect'
      preLoaderRoute: typeof ApiPikaDisconnectRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/pika/connect': {
      id: '/api/pika/connect'
      path: '/api/pika/connect'
      fullPath: '/api/pika/connect'
      preLoaderRoute: typeof ApiPikaConnectRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/asset/$id': {
      id: '/api/asset/$id'
      path: '/api/asset/$id'
      fullPath: '/api/asset/$id'
      preLoaderRoute: typeof ApiAssetIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/pika/oauth/callback': {
      id: '/api/pika/oauth/callback'
      path: '/api/pika/oauth/callback'
      fullPath: '/api/pika/oauth/callback'
      preLoaderRoute: typeof ApiPikaOauthCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  StudioRoute: StudioRoute,
  ApiChatRoute: ApiChatRoute,
  ApiAssetIdRoute: ApiAssetIdRoute,
  ApiPikaConnectRoute: ApiPikaConnectRoute,
  ApiPikaDisconnectRoute: ApiPikaDisconnectRoute,
  ApiPikaStatusRoute: ApiPikaStatusRoute,
  ApiPikaOauthCallbackRoute: ApiPikaOauthCallbackRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
