/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as StudioRouteImport } from './routes/studio'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiChatRouteImport } from './routes/api/chat'
import { Route as ApiAssetIdRouteImport } from './routes/api/asset.$id'

const StudioRoute = StudioRouteImport.update({
  id: '/studio',
  path: '/studio',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiChatRoute = ApiChatRouteImport.update({
  id: '/api/chat',
  path: '/api/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAssetIdRoute = ApiAssetIdRouteImport.update({
  id: '/api/asset/$id',
  path: '/api/asset/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/studio': typeof StudioRoute
  '/api/chat': typeof ApiChatRoute
  '/api/asset/$id': typeof ApiAssetIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/studio': typeof StudioRoute
  '/api/chat': typeof ApiChatRoute
  '/api/asset/$id': typeof ApiAssetIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/studio': typeof StudioRoute
  '/api/chat': typeof ApiChatRoute
  '/api/asset/$id': typeof ApiAssetIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/studio' | '/api/chat' | '/api/asset/$id'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/studio' | '/api/chat' | '/api/asset/$id'
  id: '__root__' | '/' | '/studio' | '/api/chat' | '/api/asset/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  StudioRoute: typeof StudioRoute
  ApiChatRoute: typeof ApiChatRoute
  ApiAssetIdRoute: typeof ApiAssetIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/studio': {
      id: '/studio'
      path: '/studio'
      fullPath: '/studio'
      preLoaderRoute: typeof StudioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/chat': {
      id: '/api/chat'
      path: '/api/chat'
      fullPath: '/api/chat'
      preLoaderRoute: typeof ApiChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/asset/$id': {
      id: '/api/asset/$id'
      path: '/api/asset/$id'
      fullPath: '/api/asset/$id'
      preLoaderRoute: typeof ApiAssetIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  StudioRoute: StudioRoute,
  ApiChatRoute: ApiChatRoute,
  ApiAssetIdRoute: ApiAssetIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
